### ISSUE TITLE
CLI translate-schema command does not work in "json-to-cedar" direction

### ISSUE THREAD

**Issue by adamrothman** [cedar-policy/cedar#1159] opened 2024-08-29 21:48 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Schemas and Validation

### Describe the bug

The CLI's `translate-schema` command fails when invoked with a JSON schema and `--direction json-to-cedar`:
```
$ cargo run -- translate-schema --schema ~/Downloads/photoflash.cedarschema.json --direction json-to-cedar
warning: /Users/adam.rothman/src/cedar/cedar-policy-core/Cargo.toml: unused manifest key: lints.rust.unexpected_cfgs.check-cfg
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
     Running `/Users/adam.rothman/src/cedar/target/debug/cedar translate-schema --schema /Users/adam.rothman/Downloads/photoflash.cedarschema.json --direction json-to-cedar`
  × error parsing schema: unexpected token `{`
  help: this API was expecting a schema in the Cedar schema format; did you mean to use a different function, which expects a JSON-format Cedar schema
```

### Expected behavior

The CLI should successfully parse the JSON schema file and output a translation to the human-readable format.

For example, it works fine when translating the [example human-readable schema](https://docs.cedarpolicy.com/schema/human-readable-schema.html#schema-examples) to JSON:
```
$ cargo run -- translate-schema --schema ~/Downloads/photoflash.cedarschema --direction cedar-to-json 
warning: /Users/adam.rothman/src/cedar/cedar-policy-core/Cargo.toml: unused manifest key: lints.rust.unexpected_cfgs.check-cfg
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.07s
     Running `/Users/adam.rothman/src/cedar/target/debug/cedar translate-schema --schema /Users/adam.rothman/Downloads/photoflash.cedarschema --direction cedar-to-json`
{"PhotoFlash":{"entityTypes":{"Album":{"memberOfTypes":["Album"],"shape":{"type":"Record","attributes":{"account":{"type":"EntityOrCommon","name":"Account"},"private":{"type":"EntityOrCommon","name":"Bool"}}}},"User":{"memberOfTypes":["UserGroup"],"shape":{"type":"Record","attributes":{"department":{"type":"EntityOrCommon","name":"String"},"jobLevel":{"type":"EntityOrCommon","name":"Long"}}}},"Account":{"shape":{"type":"Record","attributes":{"admins":{"type":"Set","element":{"type":"EntityOrCommon","name":"User"},"required":false},"owner":{"type":"EntityOrCommon","name":"User"}}}},"Photo":{"memberOfTypes":["Album"],"shape":{"type":"Record","attributes":{"account":{"type":"EntityOrCommon","name":"Account"},"private":{"type":"EntityOrCommon","name":"Bool"}}}},"UserGroup":{}},"actions":{"uploadPhoto":{"appliesTo":{"resourceTypes":["Album"],"principalTypes":["User"],"context":{"type":"Record","attributes":{"authenticated":{"type":"EntityOrCommon","name":"Bool"},"photo":{"type":"Record","attributes":{"file_size":{"type":"EntityOrCommon","name":"Long"},"file_type":{"type":"EntityOrCommon","name":"String"}}}}}}},"viewPhoto":{"appliesTo":{"resourceTypes":["Photo"],"principalTypes":["User"],"context":{"type":"Record","attributes":{"authenticated":{"type":"EntityOrCommon","name":"Bool"}}}}},"listAlbums":{"appliesTo":{"resourceTypes":["Account"],"principalTypes":["User"],"context":{"type":"Record","attributes":{"authenticated":{"type":"EntityOrCommon","name":"Bool"}}}}}}}}
```

### Reproduction steps

1. Clone https://github.com/cedar-policy/cedar at latest master (3458cd20ec56756d164faf1108c20515bb839196 at time of report)
2. Download the example JSON format schema [here](https://docs.cedarpolicy.com/schema/json-schema.html#schema-examples); attached as [photoflash.cedarschema.json](https://github.com/user-attachments/files/16806244/photoflash.cedarschema.json)
3. In the `cedar-policy-cli` directory, run `cargo run -- translate-schema --schema ~/Downloads/photoflash.cedarschema.json --direction json-to-cedar`
4. Error

### Operating  System

macOS Sonoma 14.6.1

**Comment by khieta** [comment] 2024-08-30 12:18
Thanks for reporting this! This was an unintentional break caused by #1114. I can have a fix up shortly.

**Comment by khieta** [comment] 2024-08-30 15:16
Fix is merged! Thanks again for filing the issue.

**Closed** 2024-08-30 15:16 UTC
Labels: bug, work-in-progress

**Comment by adamrothman** [comment] 2024-08-30 17:05
Thanks for turning it around so quickly!
