### ISSUE TITLE
improve some schema parsing error messages

### ISSUE THREAD

**Issue by hakanson** [cedar-policy/cedar#349] opened 2023-10-08 02:25 UTC
### Category

Cedar validation features

### Describe the feature you'd like to request

Validation / parsing the the following schema produces the error below (with no location info) because of `"memberOfTypes": [""]`

> Parse error in entity type: unexpected end of input

```json
{
  "": {
    "entityTypes": {
      "User": {
        "memberOfTypes": [""]
      }
    },
    "actions": {}
  }
}
```
---

and this schema / error (with no location info) because of `"Employee": { "shape": { "type": "String" } }`

> Action context or entity type shape is not a record

```json
{
  "": {
    "commonTypes": {
      "Person": {
        "type": "Record",
        "attributes": {
          "age": { "type": "Long" },
          "name": { "type": "String" }
        }
      }
    },
    "entityTypes": {
      "Employee": { "shape": { "type": "String" } },
      "Customer": { "shape": { "type": "Person" } }
    },
    "actions": {}
  }
}
```

### Describe alternatives you've considered

regular expressions, but then I'd have 2 problems. 😄 

### Additional context

This is easy to test via the CLI using a empty Cedar policies files

```bash
$ cedar validate --schema memberoftypes.cedarschema.json --policies blank.cedar
Error: cedar_policy_cli::other_err

  × failed to parse schema from file memberoftypes.cedarschema.json
  ╰─▶ Parse error in entity type: unexpected end of input
```

```bash
$ cedar validate --schema common.cedarschema.json --policies blank.cedar
Error: cedar_policy_cli::other_err

  × failed to parse schema from file common.cedarschema.json
  ╰─▶ Action context or entity type shape is not a record
```

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment] 2023-10-09 12:59
Partial duplicate of #174

**Comment by hakanson** [comment] 2023-10-09 16:08
Some additional examples related to schema parsing.  These are have spaces (not allowed), but error message doesn't provide that detail, nor indicate the location.

> Parse error in namespace identifier: unexpected token `Name`

```json
{
  "My Name Space": {
    "entityTypes": {},
    "actions": {}
  }
}
```

> Parse error in entity type: unexpected token `Entity`

```json
{
  "MyNameSpace": {
    "entityTypes": {
      "My Entity Type": {}
    },
    "actions": {}
  }
}
```

> Parse error in common type identifier: unexpected token `Common`

```json
{
  "MyNameSpace": {
    "commonTypes": {
      "My Common Type": {
        "type": "String"
      }
    },
    "entityTypes": {},
    "actions": {}
  }
}
```

**Comment by john-h-kastner-aws** [comment] 2023-11-15 21:24
Closing in favor of other issues:

* #174 would add source locations to these errors, but it is not likely to happen soon.
* I opened #435 proposing a more near-term concrete improvement to this class of error messages.
* The unhelpful `unexpected token` error messages come from the main policy/exprssion parers and would be improved by #176.

**Closed by john-h-kastner-aws** 2023-11-15 21:24 UTC
Labels: backlog, feature-request
