### ISSUE TITLE
Treesitter parser

### ISSUE THREAD

**Issue by liamwh** [cedar-policy/cedar#609] opened 2024-01-30 07:47 UTC
### Category

Other

### Describe the feature you'd like to request

I apologise if this is not the correct place to ask. However I would love a Cedar [treesitter parser](https://github.com/nvim-treesitter/nvim-treesitter) so Neovim users can use Cedar like VS Code users; I feel this would significantly help Cedar adoption.

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment] 2024-04-22 17:19
Duplicate of cedar-policy/highlightjs-cedar#10.  Not sure which is the better place for this discussion, but more discussion seems to be happening there.

**Comment by john-h-kastner-aws** [comment] 2024-06-05 13:29
Closing due the existence of https://github.com/chrnorm/tree-sitter-cedar

**Closed by john-h-kastner-aws** 2024-06-05 13:29 UTC
Labels: help-wanted, backlog, feature-request

**Comment by liamwh** [comment] 2024-06-06 08:28
@john-h-kastner-aws, whilst it's true that repo exists, it still isn't consumable from nvim-treesitter, please see https://github.com/chrnorm/tree-sitter-cedar/issues/1. So the problem of being able to use a treesitter parser from Neovim still exists and isn't yet solved.
