### ISSUE TITLE
CLI command to convert between Human an JSON policy formats

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#617] opened 2024-02-01 16:07 UTC
### Category

CLI features/changes

### Describe the feature you'd like to request

#575 adds a `translate-schema` subcommand for converting between the human and JSON schema formats, but we don't have this functionality for the policy formats. 

### Describe alternatives you've considered

.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment] 2024-02-01 16:35
Duplicate of #461?

**Closed** 2024-02-01 16:38 UTC
Labels: good-first-issue, backlog, feature-request
